#!/bin/sh

SRC=./src
DIST=./dist

./clean

mkdir $DIST
cp $SRC/*.html $DIST

mkdir $DIST/js
cp $SRC/js/*.js   $DIST/js/

du -shb $DIST/js/*.js

echo "Creating the zip archive..."
cd $DIST
zip -r game.zip *
cd ..


echo '-------------------------------'
du -shb $DIST/*.zip
echo '-------------------------------'
