#!/bin/sh

SRC=./src
DIST=./dist
STAGE=$DIST/stage
TAR=$DIST/target
ZIP=game.zip

echo "Cleaning..."
./clean

echo "Indexing source files..."
./index

echo "Staging the Package..."
mkdir -p $DIST
mkdir -p $STAGE
cp --verbose $SRC/html/*.html $STAGE/

cp --verbose -r $SRC/dry  $STAGE/
cp --verbose -r $SRC/zap  $STAGE/

#du -shb $STAGE/*.html
#du -shb $STAGE/js/*.js

# minify
echo "=============="
echo "=   Minify   ="
echo "=============="
mkdir -p $TAR
node ./tools/minify.js $STAGE $TAR

# just copy html fo now
# TODO minify .html and .css files
cp --verbose $STAGE/*.html $TAR


echo "============="
echo "=    ZIP    ="
echo "============="
echo "Creating the archive from [$TAR]..."
cd $TAR
pwd
zip -r $ZIP *
mv --verbose $ZIP ../
cd -

echo '-------------------------------'
du -shb $DIST/*.zip
du -sh --apparent-size $DIST/*.zip
echo '-------------------------------'
