#!/bin/bash

SRC=./mod
STAGE=./.stage.tmp
TARGET=${1:-./index.html}

cd $SRC
find . -name "*.js" | awk '{ printf "        <script src=\""; printf $1; print "\"></script>"; }' | sort > .index.tmp

cat $TARGET | grep -v '<script' | grep . > .preHTML.tmp

cat .preHTML.tmp | awk '
/DOCTYPE/{f=1}
/\/head/{exit}
f' > $STAGE

cat .index.tmp >> $STAGE

cat .preHTML.tmp | awk '
/\/head/{f=1}
f' >> $STAGE 

cat $STAGE

cp --verbose $STAGE $TARGET

