#!/bin/bash

URL=./mod/index.html

if [[ $1 == "x" ]]; then
    URL=./dist/targetX/index.html
elif [[ $1 == "y" ]]; then
    URL=./dist/targetY/index.html
elif [[ $1 == "s" ]]; then

    echo "=== Running in Staging ==="

    export SRC="./dist/stage/"
    ./index
    URL=./dist/stage/index.html

fi

nohup xdg-open $URL &>/dev/null &

