#!/bin/sh

TAR=./snap
SRC=./mod
STAGE=./dist/stage
TIMESTAMP=`date +'%F_%T'`

echo "=== Taking Stats Snapshot ==="
echo "datetime: $TIMESTAMP"
echo "saving to: $STAGE"

echo "build..."
./build > $TAR/$TIMESTAMP.build.out

echo "cloc..."
cloc $SRC > "$TAR/$TIMESTAMP.mod.cloc"
cloc $STAGE > "$TAR/$TIMESTAMP.stage.cloc"

echo "OK"

