#!/bin/bash

TAR=./mod/

if [[ $1 == "x" ]]; then
    ./build
    TAR=./dist/targetX/
elif [[ $1 == "y" ]]; then
    ./build
    TAR=./dist/targetY/
elif [[ $1 == "s" ]]; then
    ./build
    TAR=./dist/stage/
fi

# calculate word frequencies
find $TAR -name '*.js' -exec cat {} \; | sed -e  's/[^A-Za-z]/ /g' | tr 'A-Z' 'a-z' | tr ' ' '\n' | grep -v '^$'| sort | uniq -c | sort -n

